package websitebuilder;
// Generated Jun 5, 2017 7:12:50 PM by Hibernate Tools 4.3.1



/**
 * Website generated by hbm2java
 */
public class Website  implements java.io.Serializable {


     private String userId;
     private String url;
     private Boolean published;

    public Website() {
    }

	
    public Website(String userId) {
        this.userId = userId;
    }
    public Website(String userId, String url, Boolean published) {
       this.userId = userId;
       this.url = url;
       this.published = published;
    }
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Boolean getPublished() {
        return this.published;
    }
    
    public void setPublished(Boolean published) {
        this.published = published;
    }




}


